version: 2

jobs:

 build:
   docker:
      - image: docker
    
   working_directory: ~/Udagram-Image-Filtering-Microservice
   steps:
    - checkout
    - setup_remote_docker

    - run:
       name: build docker image
       command:  |

        docker -v && docker-compose -v
        docker image prune --all 
        docker-compose -f docker-compose-build.yaml build --parallel
    
    - run:
       name:  Push build Udagram-Api-Feed
       command: |
         docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
         docker push newthingade/udagram-api-feed:latest
   
   
    - run:
       name:  Push build Udagram-Api-User
       command: |
         docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
         docker push newthingade/udagram-api-user:latest
   
    - run:
       name:  Push build Udagram-Frontend
       command: |
         docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
         docker push newthingade/udagram-frontend:latest
    
    - run:
       name:  Push build Udagram-reverseproxy
       command: |
         docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
         docker push newthingade/udagram-reverseproxy:latest


workflows:
  version: 2
  default:
    jobs:
      - build
